#!/bin/bash

#############
# AUTOSTART #
#############

sxhkd &
$HOME/.config/polybar/launch.sh &
xrandr --dpi 120 &
setxkbmap jp &
picom --experimental-backend &
$HOME/.fehbg &
xsetroot -cursor_name left_ptr &
ibus-daemon -drx &
xset s on
xset s 600
xss-lock -- betterlockscreen -l dimblur &

#############
# Preferences
#############

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           10 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#######
# Rules
#######

bspc rule -a pavucontrol state=floating
